//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektOOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosci
    {
        public int Id_platnosci { get; set; }
        public string Czy_oplacona { get; set; }
        public Nullable<int> Id_polisy { get; set; }
    
        public virtual Polisy Polisy { get; set; }
    }
}
