//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektOOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polisy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polisy()
        {
            this.Platnosci = new HashSet<Platnosci>();
        }
    
        public int Id_polisy { get; set; }
        public string Kod_pakietu { get; set; }
        public Nullable<System.DateTime> Data_zawarcia { get; set; }
        public Nullable<int> Id_wlasciciela { get; set; }
        public Nullable<int> Id_pojazdu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosci> Platnosci { get; set; }
        public virtual Pojazdy Pojazdy { get; set; }
        public virtual Wlasciciele Wlasciciele { get; set; }
    }
}
